/// A generated (or reused-from-cache) editable draft of a `CatalogCampaign`'s
/// (TASK-080) textual structure — title, subtitle/headline, editorial
/// description — for one set of admin-supplied parameters (TASK-192,
/// EPIC-28). Always produced server-side by the `assistCampaignCreation`
/// Cloud Function from already-verified data (the organization's own real
/// products); never assembled client-side.
///
/// Every field here is always a *rascunho*: `tasks.md`/TASK-192: "sempre
/// como rascunho revisável antes de publicar — nunca publicando
/// automaticamente". No widget built on top of [CampaignCreationDraft]
/// should ever save/publish it directly — `CampaignFormPage` only ever
/// pre-fills its own editable title/subtitle/description fields with these
/// values, leaving the existing "Criar campanha"/"Salvar alterações" action
/// (TASK-080) as the one and only explicit publish step.
final class CampaignCreationDraft {
  const CampaignCreationDraft({
    required this.title,
    required this.subtitle,
    required this.description,
    required this.citedProductIds,
    required this.generatedAt,
    required this.expiresAt,
    required this.fromCache,
  });

  final String title;
  final String subtitle;
  final String description;

  /// Ids (among the ones the admin selected) the generated text actually
  /// names — always a subset of what was supplied, never a product outside
  /// the organization's own real catalog (`assistCampaignCreation`'s own
  /// server-side validation guarantees this before the draft ever reaches
  /// this entity).
  final List<String> citedProductIds;

  final DateTime generatedAt;
  final DateTime expiresAt;

  /// Whether this instance was served from the server-side cache (unchanged
  /// parameters, still within the TTL) rather than freshly generated by the
  /// LLM provider on this very call — purely informational.
  final bool fromCache;
}
