import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:vestipro/core/errors/errors.dart';
import 'package:vestipro/core/functions/functions.dart';
import 'package:vestipro/firebase_options.dart';

/// Real integration test against a locally running Functions Emulator
/// (TASK-015's "Teste de integração client-side chamando healthCheck via
/// Emulator Suite através do CloudFunctionsService"), exercising
/// [CloudFunctionsService] end to end against the real `healthCheck`
/// function deployed in `functions/src/health/health-check.ts` — the same
/// function is what deploys to production (ADR-0002), so this validates the
/// whole pipeline: build, emulator, wrapper, correlation id, error mapping.
///
/// `healthCheck` has no business logic and never fails on its own, so the
/// two error scenarios required by the task ("erro simulado (timeout,
/// função inexistente)") are produced without any test-only Cloud Function:
/// a nonexistent function name (a real 404 from the emulator, mapped by the
/// SDK to `functions/not-found`) and an unrealistically short client-side
/// [Duration] passed as `timeout` (a real `functions/deadline-exceeded`,
/// confirmed against the running emulator — see "Riscos conhecidos" in
/// `docs/tasks/TASK-015-configurar-cloud-functions-CONCLUIDA.md`). Shipping
/// a dedicated error-simulating callable would also have to be deployed to
/// the single real `vestipro` project (there is no staging project to keep
/// it out of, ADR-0002), which is not worth it just for this test.
///
/// Requires the emulator to already be running before this suite starts:
///
/// ```bash
/// cd functions && npm run build && cd ..
/// firebase emulators:start --only functions --project vestipro
/// # in another terminal
/// flutter test integration_test/core/functions/cloud_functions_service_integration_test.dart -d chrome
/// ```
///
/// `firebase emulators:exec "flutter test integration_test/core/functions/... -d chrome"`
/// also works and tears the emulator down automatically.
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  const emulatorHost = 'localhost';
  const emulatorPort = 5001;

  late CloudFunctionsService service;

  setUpAll(() async {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    FirebaseFunctions.instance.useFunctionsEmulator(emulatorHost, emulatorPort);
  });

  setUp(() {
    service = CloudFunctionsService.withDependencies(
      FirebaseFunctions.instance,
      FirebaseAuth.instance,
      PackageInfoClientMetadataProvider(),
    );
  });

  testWidgets('healthCheck against the real emulator returns ok and echoes the '
      'correlation id generated by the wrapper', (tester) async {
    final response = await service.call<Map<String, dynamic>>('healthCheck');

    expect(response['status'], 'ok');
    expect(response['authenticated'], false);
    final correlationId = response['correlationId'] as String;
    expect(correlationId, isNotEmpty);
    expect(response['serverTimestamp'], isA<String>());
  });

  testWidgets(
    'calling a function that does not exist maps to NotFoundException '
    'end-to-end',
    (tester) async {
      await expectLater(
        service.call<Map<String, dynamic>>('thisFunctionDoesNotExist'),
        throwsA(isA<NotFoundException>()),
      );
    },
  );

  testWidgets(
    'an unrealistically short timeout maps to NetworkException end-to-end, '
    'after CloudFunctionsService retries the transient deadline-exceeded '
    'error',
    (tester) async {
      await expectLater(
        service.call<Map<String, dynamic>>(
          'healthCheck',
          timeout: const Duration(milliseconds: 1),
        ),
        throwsA(isA<NetworkException>()),
      );
    },
  );
}
