import '../../domain/entities/report_definition.dart';
import '../../domain/entities/report_export_result.dart';

sealed class ReportBuilderEvent {
  const ReportBuilderEvent();
}

final class ReportBuilderStarted extends ReportBuilderEvent {
  const ReportBuilderStarted({
    required this.organizationId,
    required this.companyId,
    required this.userId,
  });
  final String organizationId;
  final String companyId;
  final String userId;
}

final class ReportDimensionToggled extends ReportBuilderEvent {
  const ReportDimensionToggled(this.id);
  final String id;
}

final class ReportMetricToggled extends ReportBuilderEvent {
  const ReportMetricToggled(this.id);
  final String id;
}

final class ReportFilterChanged extends ReportBuilderEvent {
  const ReportFilterChanged(this.filter);
  final ReportFilter filter;
}

final class ReportComparisonChanged extends ReportBuilderEvent {
  const ReportComparisonChanged(this.value);
  final ReportComparisonPeriod value;
}

final class ReportSortChanged extends ReportBuilderEvent {
  const ReportSortChanged(this.value);
  final ReportSort? value;
}

final class ReportExecutionRequested extends ReportBuilderEvent {
  const ReportExecutionRequested();
}

final class ReportBuilderRetried extends ReportBuilderEvent {
  const ReportBuilderRetried();
}

/// Requests exporting `ReportBuilderState.preview` to CSV (TASK-146) or XLSX
/// (TASK-147) — a no-op unless a preview is already loaded
/// (`ReportExecutionRequested` must have already succeeded). Defaults to
/// [ReportExportFormat.csv] to keep existing call sites/tests unchanged.
/// Never used for [ReportExportFormat.pdf] — that format always goes
/// through [ReportPdfPreviewRequested]/[ReportPdfExportConfirmed] instead
/// (TASK-148's mandatory pré-visualização step).
final class ReportExportRequested extends ReportBuilderEvent {
  const ReportExportRequested({this.format = ReportExportFormat.csv});
  final ReportExportFormat format;
}

/// Requests a PDF pré-visualização (TASK-148) — generates the file (or, for
/// a large result, delegates the whole export to the `exportReportToPdf`
/// Cloud Function) without saving anything locally yet.
final class ReportPdfPreviewRequested extends ReportBuilderEvent {
  const ReportPdfPreviewRequested();
}

/// The user closed the PDF preview without confirming the export
/// (TASK-148's "permite cancelar antes de gerar o arquivo final" acceptance
/// criterion) — discards the already-generated bytes, nothing is saved.
final class ReportPdfPreviewCancelled extends ReportBuilderEvent {
  const ReportPdfPreviewCancelled();
}

/// The user confirmed a PDF preview already shown
/// (`ReportBuilderState.pdfPreview`) — saves the *same* bytes the preview
/// rendered, never re-encoding the report or re-resolving branding.
final class ReportPdfExportConfirmed extends ReportBuilderEvent {
  const ReportPdfExportConfirmed();
}
