import '../../../../core/utils/utils.dart';
import '../entities/catalog_share.dart';
import '../entities/catalog_share_item.dart';
import '../entities/issued_catalog_share.dart';
import '../value_objects/catalog_share_scope.dart';

/// Contract for creating and managing [CatalogShare]s from the **vendor's**
/// side (TASK-081, EPIC-10) — always authenticated, always scoped by
/// [organizationId], so no call can be built without a tenant scope by
/// mistake, same invariant [InviteRepository] already documents for
/// `lib/features/invites`.
///
/// The real authorization/token-generation decision is always the
/// `createCatalogShareLink`/`revokeCatalogShareLink` Cloud Functions
/// (re-validated from the caller's real Membership), never this contract by
/// itself (`AGENTS.md`: "nunca confiar apenas no organizationId vindo do
/// cliente").
abstract interface class CatalogShareRepository {
  /// Creates a new [CatalogShare] scoped by [scope]/[items] (and
  /// [collectionId]/[collectionName] when [scope] is
  /// [CatalogShareScope.collection]), returning the persisted record plus
  /// the plaintext token needed to build the shareable link right now.
  ///
  /// [expiresInDays] is clamped/defaulted server-side — passing `null` uses
  /// the server's own default (30 days today).
  Future<AppResult<IssuedCatalogShare>> create({
    required String organizationId,
    required CatalogShareScope scope,
    required List<CatalogShareItem> items,
    String? collectionId,
    String? collectionName,
    int? expiresInDays,
  });

  /// Revokes [shareId], invalidating its link immediately. Only the share's
  /// own creator, or an OWNER/ADMIN of [organizationId], may succeed —
  /// enforced server-side by `revokeCatalogShareLink`.
  Future<AppResult<CatalogShare>> revoke({
    required String organizationId,
    required String shareId,
  });

  /// Re-reads [shareId] — used to refresh `openCount`/`lastOpenedAt` on the
  /// origin screen after a share was created (TASK-081: "vendedor consegue
  /// ver, na origem do compartilhamento, se e quando o link foi aberto").
  /// A direct Firestore read gated by `firestore.rules` to the share's own
  /// creator (or an OWNER/ADMIN), not a Cloud Function — no token/authority
  /// is generated by this call, so there is nothing here that needs to run
  /// server-side beyond the Rules check itself, same precedent
  /// `InviteRepository.listPending` already sets for `invites`.
  Future<AppResult<CatalogShare>> getById({
    required String organizationId,
    required String shareId,
  });
}
