import 'package:injectable/injectable.dart';

import '../../../../core/errors/errors.dart';
import '../../../../core/permissions/permissions.dart';
import '../../../../core/utils/utils.dart';
import '../entities/exchange_request_item.dart';
import '../entities/exchange_request_submission_result.dart';
import '../repositories/exchange_request_repository.dart';
import '../value_objects/exchange_reason_category.dart';

/// Opens a troca request against an already-fulfilled pedido (TASK-200,
/// EPIC-30) — re-checks [Capability.exchangeRequestCreate] here as
/// defense-in-depth, same precedent `CreateReturnRequestUseCase` (TASK-199)
/// already follows; `createExchangeRequest` (Cloud Function) remains the
/// real, independent source of truth for both the capability and the
/// seller/pedido-ownership scope, plus the destination variant's real-time
/// availability.
///
/// [exchangeRequestId] is generated by the caller
/// (`ExchangeRequestFormCubit`), never by this use case.
@injectable
final class CreateExchangeRequestUseCase {
  const CreateExchangeRequestUseCase(this._repository, this._permissionService);

  final ExchangeRequestRepository _repository;
  final PermissionService _permissionService;

  Future<AppResult<ExchangeRequestSubmissionResult>> call({
    required String organizationId,
    required String companyId,
    required String userId,
    required String orderId,
    required String exchangeRequestId,
    required List<ExchangeRequestItemInput> items,
    required ExchangeReasonCategory reasonCategory,
    String? reasonDetails,
  }) async {
    if (items.isEmpty) {
      return const AppFailure<ExchangeRequestSubmissionResult>(
        ValidationFailure(
          'Selecione ao menos um item para trocar.',
          fieldErrors: <String, String>{
            'items': 'Selecione ao menos um item para trocar.',
          },
          code: 'exchange_request_items_required',
        ),
      );
    }
    if (items.any((item) => item.quantity <= 0)) {
      return const AppFailure<ExchangeRequestSubmissionResult>(
        ValidationFailure(
          'A quantidade de cada item deve ser maior que zero.',
          fieldErrors: <String, String>{
            'items': 'A quantidade de cada item deve ser maior que zero.',
          },
          code: 'exchange_request_invalid_quantity',
        ),
      );
    }
    if (items.any((item) => item.destinationVariantId.trim().isEmpty)) {
      return const AppFailure<ExchangeRequestSubmissionResult>(
        ValidationFailure(
          'Selecione a variante de destino de cada item.',
          fieldErrors: <String, String>{
            'items': 'Selecione a variante de destino de cada item.',
          },
          code: 'exchange_request_destination_required',
        ),
      );
    }

    final permissionResult = await _permissionService.hasPermission(
      organizationId: organizationId,
      userId: userId,
      capability: Capability.exchangeRequestCreate,
    );
    if (permissionResult is AppFailure<bool>) {
      return AppFailure<ExchangeRequestSubmissionResult>(
        permissionResult.failure,
      );
    }
    if (!(permissionResult as AppSuccess<bool>).value) {
      return const AppFailure<ExchangeRequestSubmissionResult>(
        PermissionFailure(
          'Seu perfil não pode solicitar trocas.',
          code: 'exchange_request_create_denied',
        ),
      );
    }

    return _repository.createExchangeRequest(
      organizationId: organizationId,
      companyId: companyId,
      orderId: orderId,
      exchangeRequestId: exchangeRequestId,
      items: items,
      reasonCategory: reasonCategory,
      reasonDetails: reasonDetails,
    );
  }
}
