import 'approach_suggestion_reference.dart';

/// A generated (or reused-from-cache) short commercial-approach draft for
/// one customer (TASK-187, EPIC-28). Always produced server-side by the
/// `suggestApproach` Cloud Function from already-verified data (recent
/// orders, recent CRM activities, active insights); never assembled
/// client-side.
///
/// [suggestedText] is always a *rascunho*: `tasks.md`/TASK-187: "A sugestão
/// é sempre um rascunho editável; nunca dispara mensagem ou ação
/// automaticamente". No widget built on top of [ApproachSuggestion] should
/// ever send it anywhere without the seller reviewing/editing it first (see
/// `ApproachSuggestionSheet`, which always opens the text in an editable
/// field before any "usar como atividade" action).
final class ApproachSuggestion {
  const ApproachSuggestion({
    required this.suggestedText,
    required this.references,
    required this.generatedAt,
    required this.expiresAt,
    required this.fromCache,
  });

  final String suggestedText;
  final List<ApproachSuggestionReference> references;
  final DateTime generatedAt;
  final DateTime expiresAt;

  /// Whether this instance was served from the server-side cache
  /// (unchanged data, still within the TTL) rather than freshly generated by
  /// the LLM provider on this very call — purely informational.
  final bool fromCache;
}
