import 'wallet_summary_reference.dart';

/// A generated (or reused-from-cache) natural-language summary of one
/// seller's carteira — destaques, riscos e oportunidades (TASK-186,
/// EPIC-28). Always produced server-side by the `generateWalletSummary`
/// Cloud Function from already-computed data; never assembled or mutated
/// client-side.
///
/// [summaryText] is purely informational — `tasks.md`/TASK-186: "O resumo é
/// somente informativo — nunca aciona automaticamente uma ação comercial
/// (desconto, contato, pedido)". No UI built on top of [WalletSummary]
/// should ever treat it as anything more than read-only narrative context.
final class WalletSummary {
  const WalletSummary({
    required this.summaryText,
    required this.references,
    required this.periodKey,
    required this.generatedAt,
    required this.expiresAt,
    required this.fromCache,
  });

  final String summaryText;
  final List<WalletSummaryReference> references;

  /// `YYYY-MM` of the period this summary covers.
  final String periodKey;
  final DateTime generatedAt;
  final DateTime expiresAt;

  /// Whether this instance was served from the server-side cache
  /// (unchanged data, still within the TTL) rather than freshly generated by
  /// the LLM provider on this very call — purely informational, shown in the
  /// UI as "gerado às HH:mm" either way.
  final bool fromCache;
}
