import 'package:freezed_annotation/freezed_annotation.dart';

part 'order_item.freezed.dart';

/// One product-color-size variant line inside an `Order` (EPIC-13,
/// TASK-095).
///
/// [unitPrice] is always the price returned by the pricing engine
/// (`ResolvePriceForVariantUseCase`, TASK-088) at the moment the item is
/// added to the order — it is captured here and never recalculated
/// retroactively without an explicit audit trail; a later price change to
/// the same variant/Price List must not silently change an item already on
/// an order. [subtotal] is likewise a captured value (`quantity * unitPrice`
/// adjusted by [discountAmount]/[surchargeAmount]), not a derived getter,
/// for the same auditability reason — whichever later task computes it must
/// still store the result here rather than let every reader recompute it.
///
/// No submission, pricing or approval rule is implemented in this task: this
/// entity only models the shape TASK-096 onward will fill in.
///
/// [packId]/[packCode]/[packVersion]/[packGroupId]/[packName] (TASK-208,
/// EPIC-32) are only set when this item was generated by expanding a
/// `CommercialPack` (`ExpandCommercialPackToOrderItemsUseCase`) — every
/// `null` for a plain catalog-picked item, same "absent means not
/// applicable" convention every other optional `OrderItem` field already
/// follows. [packGroupId] is the one field that actually matters
/// operationally: every item sharing the same [packGroupId] came from the
/// very same "adicionar pacote ao pedido" action, so removing/explaining one
/// pack instance means acting on every item with that same id — never
/// matched by [packId] alone, since two separate instances of the *same*
/// pack added to the same order share [packId]/[packCode]/[packVersion] but
/// never [packGroupId]. [packCode]/[packVersion]/[packName] are a snapshot
/// of the pack exactly as it was when added (never re-read from the pack's
/// current, possibly revised, document later) — the "rastreabilidade de
/// qual pacote/versão originou cada item" this task's acceptance criteria
/// requires.
@freezed
abstract class OrderItem with _$OrderItem {
  const OrderItem._();

  const factory OrderItem({
    required String id,
    required String variantId,
    // Denormalized from the variant's product for display without a join.
    required String productId,
    required int quantity,
    required double unitPrice,
    @Default(0) double discountAmount,
    @Default(0) double surchargeAmount,
    required double subtotal,
    String? packId,
    String? packCode,
    int? packVersion,
    String? packGroupId,
    String? packName,
  }) = _OrderItem;

  /// Whether this item was generated by expanding a `CommercialPack`
  /// (TASK-208) rather than picked directly from the catalog.
  bool get isFromCommercialPack => packGroupId != null;

  /// `quantity * unitPrice`, before [discountAmount]/[surchargeAmount] — a
  /// convenience for UI/validation, never a substitute for the captured
  /// [subtotal] itself.
  double get grossAmount => quantity * unitPrice;
}
