import 'package:injectable/injectable.dart';

import '../../../../core/errors/errors.dart';
import '../../../../core/permissions/permissions.dart';
import '../../../../core/utils/utils.dart';
import '../entities/post_sale_event_submission_result.dart';
import '../repositories/post_sale_event_repository.dart';
import '../value_objects/post_sale_event_type.dart';

/// Registers a manual pós-venda milestone (TASK-201, EPIC-30) — re-checks
/// [Capability.postSaleEventRegister] here as defense-in-depth, same
/// precedent [CreateReturnRequestUseCase] already follows;
/// `registerPostSaleEvent` (Cloud Function) remains the real, independent
/// source of truth for both the capability and the seller/pedido-ownership
/// scope.
///
/// [eventId] is generated by the caller (`RegisterPostSaleEventCubit`), never
/// by this use case, same precedent `ReturnRequestFormCubit`'s own
/// `returnRequestId` already sets.
@injectable
final class RegisterPostSaleEventUseCase {
  const RegisterPostSaleEventUseCase(this._repository, this._permissionService);

  final PostSaleEventRepository _repository;
  final PermissionService _permissionService;

  Future<AppResult<PostSaleEventSubmissionResult>> call({
    required String organizationId,
    required String companyId,
    required String userId,
    required String orderId,
    required String eventId,
    required PostSaleEventType type,
    String? description,
  }) async {
    if (!type.isManual) {
      return const AppFailure<PostSaleEventSubmissionResult>(
        ValidationFailure(
          'Este marco não pode ser registrado manualmente.',
          fieldErrors: <String, String>{
            'type': 'Este marco não pode ser registrado manualmente.',
          },
          code: 'post_sale_event_type_not_manual',
        ),
      );
    }
    final normalizedDescription = description?.trim();
    if (type.requiresDescription &&
        (normalizedDescription == null || normalizedDescription.isEmpty)) {
      return const AppFailure<PostSaleEventSubmissionResult>(
        ValidationFailure(
          'Descreva o problema reportado — nunca um evento vazio.',
          fieldErrors: <String, String>{
            'description':
                'Descreva o problema reportado — nunca um evento vazio.',
          },
          code: 'post_sale_event_description_required',
        ),
      );
    }

    final permissionResult = await _permissionService.hasPermission(
      organizationId: organizationId,
      userId: userId,
      capability: Capability.postSaleEventRegister,
    );
    if (permissionResult is AppFailure<bool>) {
      return AppFailure<PostSaleEventSubmissionResult>(
        permissionResult.failure,
      );
    }
    if (!(permissionResult as AppSuccess<bool>).value) {
      return const AppFailure<PostSaleEventSubmissionResult>(
        PermissionFailure(
          'Seu perfil não pode registrar eventos de pós-venda.',
          code: 'post_sale_event_register_denied',
        ),
      );
    }

    return _repository.registerPostSaleEvent(
      organizationId: organizationId,
      companyId: companyId,
      orderId: orderId,
      eventId: eventId,
      type: type,
      description: normalizedDescription,
    );
  }
}
