/// The three filterable buckets the notification center (TASK-151) groups
/// every internal notification into, matching VESTI-110/111/112: `crm`
/// (TASK-152, follow-up/activity reminders), `commercial` (TASK-153 —
/// metas, pedidos, oportunidades; also what TASK-149's target alerts use
/// today, since a metas alert is a commercial event) and `system` (anything
/// generated by the app/platform itself, not tied to a CRM or commercial
/// event).
enum AppNotificationCategory { crm, commercial, system }

/// How urgently a notification needs the recipient's attention (TASK-153).
///
/// This is deliberately independent from [AppNotificationCategory]: a
/// `commercial` notification can be either [critical] (e.g. meta em risco
/// alto, pedido rejeitado, falha crítica de sincronização) or [informative]
/// (e.g. meta próxima de ser atingida, oportunidade comercial identificada
/// pela engine de insights). Every caller that predates TASK-153 (TASK-149's
/// target alerts below `highRisk`, TASK-152's CRM reminders) keeps defaulting
/// to [informative] — nothing downgrades silently.
enum AppNotificationPriority { critical, informative }

/// Internal notification persisted for the in-app notification center
/// (TASK-151), mapped to
/// `organizations/{organizationId}/notifications/{notificationId}`.
final class AppNotification {
  const AppNotification({
    required this.id,
    required this.organizationId,
    required this.userId,
    required this.category,
    required this.title,
    required this.body,
    required this.deepLink,
    required this.createdAt,
    this.readAt,
    this.priority = AppNotificationPriority.informative,
    this.deliverAt,
    this.customerId,
  });

  final String id;
  final String organizationId;
  final String userId;
  final AppNotificationCategory category;
  final String title;
  final String body;
  final String deepLink;
  final DateTime createdAt;
  final DateTime? readAt;
  final AppNotificationPriority priority;

  /// `null` (the default, and every notification written before TASK-155)
  /// means this notification is visible as soon as it is created — the only
  /// behavior that existed before quiet hours.
  ///
  /// A non-null value means this notification was suppressed by the
  /// recipient's own quiet hours (`QuietHours.isActiveAt`) at the moment it
  /// was generated: it is already durably persisted (never lost, never
  /// dropped) but `NotificationInboxRepository.listForUser` hides it from
  /// [userId] until `DateTime.now().toUtc()` reaches this instant, at which
  /// point it becomes visible on the very next load — no separate "flush"
  /// job needs to run for it to eventually appear. Critical notifications
  /// (see [AppNotificationPriority.critical]) never set this field, even
  /// when generated during quiet hours — TASK-154/TASK-155's "notificações
  /// críticas de segurança/sessão não são bloqueadas" exception.
  final DateTime? deliverAt;

  /// Customer targeted by a commercial communication, when applicable.
  /// The backend still revalidates tenant and opt-in before sending.
  final String? customerId;

  /// Whether this notification is already visible to [userId] at
  /// [now] (defaults to the real current instant) — `false` only while
  /// [deliverAt] is still in the future.
  bool isVisibleAt([DateTime? now]) {
    final deliverAtInstant = deliverAt;
    if (deliverAtInstant == null) return true;
    return !(now ?? DateTime.now()).toUtc().isBefore(deliverAtInstant);
  }
}
