/// The three filterable buckets the notification center (TASK-151) groups
/// every internal notification into, matching VESTI-110/111/112: `crm`
/// (TASK-152, follow-up/activity reminders), `commercial` (TASK-153 —
/// metas, pedidos, oportunidades; also what TASK-149's target alerts use
/// today, since a metas alert is a commercial event) and `system` (anything
/// generated by the app/platform itself, not tied to a CRM or commercial
/// event).
enum AppNotificationCategory { crm, commercial, system }

/// How urgently a notification needs the recipient's attention (TASK-153).
///
/// This is deliberately independent from [AppNotificationCategory]: a
/// `commercial` notification can be either [critical] (e.g. meta em risco
/// alto, pedido rejeitado, falha crítica de sincronização) or [informative]
/// (e.g. meta próxima de ser atingida, oportunidade comercial identificada
/// pela engine de insights). Every caller that predates TASK-153 (TASK-149's
/// target alerts below `highRisk`, TASK-152's CRM reminders) keeps defaulting
/// to [informative] — nothing downgrades silently.
enum AppNotificationPriority { critical, informative }

/// Internal notification persisted for the in-app notification center
/// (TASK-151), mapped to
/// `organizations/{organizationId}/notifications/{notificationId}`.
final class AppNotification {
  const AppNotification({
    required this.id,
    required this.organizationId,
    required this.userId,
    required this.category,
    required this.title,
    required this.body,
    required this.deepLink,
    required this.createdAt,
    this.readAt,
    this.priority = AppNotificationPriority.informative,
  });

  final String id;
  final String organizationId;
  final String userId;
  final AppNotificationCategory category;
  final String title;
  final String body;
  final String deepLink;
  final DateTime createdAt;
  final DateTime? readAt;
  final AppNotificationPriority priority;
}
