import 'report_explanation_reference.dart';

/// A generated (or reused-from-cache) natural-language explanation of one
/// already-executed report/dashboard (TASK-189, EPIC-28) — narrates the
/// tendências/destaques of numbers `ReportDefinition`'s own aggregation
/// (TASK-133/TASK-144) already computed. Always produced server-side by the
/// `explainReport` Cloud Function, which re-derives the report's rows itself
/// (never trusting a `ReportQueryResult` the client sends) before narrating
/// them; never assembled or mutated client-side.
///
/// [explanationText] is purely descriptive — `tasks.md`/TASK-189: "a
/// explicação nunca é fonte de verdade dos números — o gráfico/tabela
/// permanece a fonte, o texto apenas narra". No UI built on top of
/// [ReportExplanation] should ever treat it as anything more than read-only
/// narrative context alongside the chart/table it explains.
final class ReportExplanation {
  const ReportExplanation({
    required this.explanationText,
    required this.references,
    required this.periodKey,
    required this.generatedAt,
    required this.expiresAt,
    required this.fromCache,
  });

  final String explanationText;
  final List<ReportExplanationReference> references;

  /// `YYYY-MM` of the period this explanation refers to.
  final String periodKey;
  final DateTime generatedAt;
  final DateTime expiresAt;

  /// Whether this instance was served from the server-side cache
  /// (unchanged data, still within the TTL) rather than freshly generated by
  /// the LLM provider on this very call — purely informational, shown in the
  /// UI as "gerado às HH:mm" either way.
  final bool fromCache;
}
