import 'package:injectable/injectable.dart';

import '../../../../core/errors/errors.dart';
import '../../../../core/permissions/permissions.dart';
import '../../../../core/utils/utils.dart';
import '../entities/return_request_item.dart';
import '../entities/return_request_submission_result.dart';
import '../repositories/return_request_repository.dart';
import '../value_objects/return_reason_category.dart';

/// Opens a devolução request against an already-fulfilled pedido (TASK-199,
/// EPIC-30) — re-checks [Capability.returnRequestCreate] here as
/// defense-in-depth, same precedent [GetOrderByIdUseCase]/
/// `DecideOrderApprovalUseCase`-equivalents already follow across this
/// codebase; `createReturnRequest` (Cloud Function) remains the real,
/// independent source of truth for both the capability and the
/// seller/pedido-ownership scope.
///
/// [returnRequestId] is generated by the caller (`ReturnRequestFormCubit`),
/// never by this use case — the same id is also used to build the optional
/// evidence photo's Storage path (`StoragePaths.returnRequestEvidence`)
/// *before* this call happens, so both must agree on it upfront.
@injectable
final class CreateReturnRequestUseCase {
  const CreateReturnRequestUseCase(this._repository, this._permissionService);

  final ReturnRequestRepository _repository;
  final PermissionService _permissionService;

  Future<AppResult<ReturnRequestSubmissionResult>> call({
    required String organizationId,
    required String companyId,
    required String userId,
    required String orderId,
    required String returnRequestId,
    required List<ReturnRequestItemInput> items,
    required ReturnReasonCategory reasonCategory,
    String? reasonDetails,
    List<String> evidenceUrls = const <String>[],
  }) async {
    if (items.isEmpty) {
      return const AppFailure<ReturnRequestSubmissionResult>(
        ValidationFailure(
          'Selecione ao menos um item para devolver.',
          fieldErrors: <String, String>{
            'items': 'Selecione ao menos um item para devolver.',
          },
          code: 'return_request_items_required',
        ),
      );
    }
    if (items.any((item) => item.quantity <= 0)) {
      return const AppFailure<ReturnRequestSubmissionResult>(
        ValidationFailure(
          'A quantidade de cada item deve ser maior que zero.',
          fieldErrors: <String, String>{
            'items': 'A quantidade de cada item deve ser maior que zero.',
          },
          code: 'return_request_invalid_quantity',
        ),
      );
    }

    final permissionResult = await _permissionService.hasPermission(
      organizationId: organizationId,
      userId: userId,
      capability: Capability.returnRequestCreate,
    );
    if (permissionResult is AppFailure<bool>) {
      return AppFailure<ReturnRequestSubmissionResult>(
        permissionResult.failure,
      );
    }
    if (!(permissionResult as AppSuccess<bool>).value) {
      return const AppFailure<ReturnRequestSubmissionResult>(
        PermissionFailure(
          'Seu perfil não pode solicitar devoluções.',
          code: 'return_request_create_denied',
        ),
      );
    }

    return _repository.createReturnRequest(
      organizationId: organizationId,
      companyId: companyId,
      orderId: orderId,
      returnRequestId: returnRequestId,
      items: items,
      reasonCategory: reasonCategory,
      reasonDetails: reasonDetails,
      evidenceUrls: evidenceUrls,
    );
  }
}
